# Generated by Django 5.0.3 on 2024-04-04 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(max_length=255, null=True)),
                ('selfie_camera', models.CharField(max_length=255, null=True)),
                ('main_camera', models.CharField(max_length=255, null=True)),
                ('display', models.CharField(max_length=255, null=True)),
                ('os', models.CharField(max_length=255, null=True)),
                ('network', models.CharField(max_length=255, null=True)),
                ('ram', models.CharField(max_length=255, null=True)),
                ('hdd', models.CharField(max_length=255, null=True)),
                ('special_feature', models.CharField(max_length=255, null=True)),
                ('battery', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
